version: 2.1
jobs:
  test-python-bloom-bindings:
    resource_class: small
    docker:
      - image: cimg/go:1.19
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            curl "https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh" --output miniconda.sh
            bash miniconda.sh -b -p .venv
            rm miniconda.sh
            source .venv/etc/profile.d/conda.sh
            
            make python-environment
            make python-build
            make python-install
            make python-tests

workflows:
  main:
    jobs:
      - test-python-bloom-bindings
